# Generated by Django 6.0.5 on 2026-06-23 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "apellido",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="apellido"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de alta"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Opcional: cuenta con la que este empleado inicia sesion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleado",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario para login",
                    ),
                ),
            ],
            options={
                "verbose_name": "empleado",
                "verbose_name_plural": "empleados",
                "db_table": "empleados",
                "ordering": ("apellido", "nombre"),
            },
        ),
    ]
