# Generated by Django 6.0.5 on 2026-06-26 22:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, verbose_name="nombre / razon social"
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("responsable_inscripto", "Responsable Inscripto"),
                            ("monotributista", "Monotributista"),
                        ],
                        default="responsable_inscripto",
                        max_length=30,
                        verbose_name="condicion fiscal",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El CUIT debe tener 11 digitos (sin guiones).",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Punto de venta habilitado para Web Services en ARCA.",
                        verbose_name="punto de venta",
                    ),
                ),
                (
                    "certificado",
                    models.TextField(
                        blank=True,
                        help_text="Contenido PEM del certificado emitido por ARCA.",
                        verbose_name="certificado (.crt/.pem)",
                    ),
                ),
                (
                    "clave_privada",
                    models.TextField(
                        blank=True,
                        help_text="Contenido PEM de la clave privada del certificado.",
                        verbose_name="clave privada (.key)",
                    ),
                ),
                (
                    "produccion",
                    models.BooleanField(
                        default=False,
                        help_text="Apagado = homologacion (testing, sin CAE real). Encendido = produccion (CAE con valor fiscal).",
                        verbose_name="produccion",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "emisor",
                "verbose_name_plural": "emisores",
                "db_table": "facturacion_emisores",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "Factura A"),
                            ("B", "Factura B"),
                            ("C", "Factura C"),
                        ],
                        max_length=1,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "concepto",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Productos"),
                            (2, "Servicios"),
                            (3, "Productos y Servicios"),
                        ],
                        default=1,
                        verbose_name="concepto",
                    ),
                ),
                (
                    "punto_venta",
                    models.PositiveIntegerField(verbose_name="punto de venta"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Numero autorizado por ARCA.", verbose_name="numero"
                    ),
                ),
                (
                    "cliente_nombre",
                    models.CharField(max_length=160, verbose_name="cliente"),
                ),
                (
                    "cliente_doc_tipo",
                    models.CharField(
                        choices=[
                            ("CUIT", "CUIT"),
                            ("CUIL", "CUIL"),
                            ("DNI", "DNI"),
                            ("CF", "Consumidor Final"),
                        ],
                        default="CF",
                        max_length=4,
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "cliente_doc_numero",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="numero de documento"
                    ),
                ),
                (
                    "cliente_condicion",
                    models.CharField(
                        choices=[
                            ("responsable_inscripto", "Responsable Inscripto"),
                            ("monotributista", "Monotributista"),
                            ("consumidor_final", "Consumidor Final"),
                            ("exento", "Exento"),
                        ],
                        default="consumidor_final",
                        max_length=30,
                        verbose_name="condicion del cliente",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de emision",
                    ),
                ),
                (
                    "vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="vencimiento de pago"
                    ),
                ),
                (
                    "alicuota_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("21"),
                        max_digits=5,
                        verbose_name="alicuota de IVA (%)",
                    ),
                ),
                (
                    "neto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="neto gravado",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="IVA"
                    ),
                ),
                (
                    "importe_exento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="exento",
                    ),
                ),
                (
                    "importe_no_gravado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="no gravado",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="total"
                    ),
                ),
                (
                    "cae",
                    models.CharField(blank=True, max_length=14, verbose_name="CAE"),
                ),
                (
                    "cae_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="vencimiento del CAE"
                    ),
                ),
                ("qr_url", models.TextField(blank=True, verbose_name="URL del QR")),
                (
                    "respuesta_afip",
                    models.JSONField(
                        blank=True, null=True, verbose_name="respuesta de ARCA"
                    ),
                ),
                (
                    "estado_cobro",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("pagada", "Pagada")],
                        default="pendiente",
                        max_length=12,
                        verbose_name="estado de cobro",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comprobantes",
                        to="facturacion.emisor",
                        verbose_name="emisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "comprobante",
                "verbose_name_plural": "comprobantes",
                "db_table": "facturacion_comprobantes",
                "ordering": ("-fecha", "-numero", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ItemComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="descripcion"),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio unitario (neto)",
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.comprobante",
                        verbose_name="comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "item del comprobante",
                "verbose_name_plural": "items del comprobante",
                "db_table": "facturacion_items",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TicketAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        default="wsfe", max_length=20, verbose_name="servicio"
                    ),
                ),
                (
                    "produccion",
                    models.BooleanField(default=False, verbose_name="produccion"),
                ),
                ("token", models.TextField(verbose_name="token")),
                ("sign", models.TextField(verbose_name="sign")),
                (
                    "generado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="generado"
                    ),
                ),
                ("expiracion", models.DateTimeField(verbose_name="expiracion")),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets_acceso",
                        to="facturacion.emisor",
                        verbose_name="emisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket de acceso",
                "verbose_name_plural": "tickets de acceso",
                "db_table": "facturacion_tickets_acceso",
            },
        ),
        migrations.AddConstraint(
            model_name="comprobante",
            constraint=models.UniqueConstraint(
                fields=("emisor", "tipo", "punto_venta", "numero"),
                name="uniq_comprobante_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketacceso",
            constraint=models.UniqueConstraint(
                fields=("emisor", "servicio"), name="uniq_ta_emisor_servicio"
            ),
        ),
    ]
