# Generated by Django 6.0.5 on 2026-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_limitemensual"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AddField(
            model_name="comprobante",
            name="cliente_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email del cliente"
            ),
        ),
    ]
