# Generated by Django 6.0.5 on 2026-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_cliente_email_comprobante_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emisor",
            name="responsable_yb",
            field=models.BooleanField(
                default=False, verbose_name="responsable Yerba Buena"
            ),
        ),
    ]
