# Generated by Django 6.0.5 on 2026-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0008_seed_conceptos"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobante",
            name="medio_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("transf_financiera", "Transferencia financiera"),
                    ("tarjeta", "Tarjeta"),
                    ("otro", "Otro"),
                ],
                default="",
                help_text="Con que se cobro. Dato interno para el resumen mensual; no viaja a ARCA.",
                max_length=20,
                verbose_name="medio de cobro",
            ),
        ),
    ]
