# Generated by Django 6.0.5 on 2026-08-23 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0009_comprobante_medio_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comprobante",
            name="uniq_comprobante_numero",
        ),
        migrations.AddField(
            model_name="comprobante",
            name="clase",
            field=models.CharField(
                choices=[("factura", "Factura"), ("nota_credito", "Nota de crédito")],
                db_index=True,
                default="factura",
                help_text='Factura o nota de credito. La letra (A/B/C) va aparte, en "tipo".',
                max_length=20,
                verbose_name="clase",
            ),
        ),
        migrations.AddField(
            model_name="comprobante",
            name="comprobante_asociado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_credito",
                to="facturacion.comprobante",
                verbose_name="factura acreditada",
            ),
        ),
        migrations.AddConstraint(
            model_name="comprobante",
            constraint=models.UniqueConstraint(
                fields=("emisor", "clase", "tipo", "punto_venta", "numero"),
                name="uniq_comprobante_numero",
            ),
        ),
    ]
