# Generated by Django 6.0.5 on 2026-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alter_movimientostock_tipo_venta_itemventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockproducto",
            name="sin_dato",
            field=models.BooleanField(
                default=False,
                help_text="La planilla de origen no informaba cantidad: el 0 no es un conteo. Se limpia solo al cargar una cantidad real.",
                verbose_name="sin dato (no informado)",
            ),
        ),
    ]
