# Generated by Django 6.0.5 on 2026-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0008_seed_stock_iphones"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="facturacion",
            field=models.CharField(
                choices=[
                    ("factura_ri", "Factura A/B (Responsable Inscripto)"),
                    ("factura_c", "Factura C (Monotributo)"),
                    ("sin_factura", "Sin factura"),
                ],
                default="sin_factura",
                max_length=20,
                verbose_name="facturacion",
            ),
        ),
    ]
