# Generated by Django 6.0.5 on 2026-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_venta_facturacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientostock",
            name="resultante",
            field=models.IntegerField(verbose_name="cantidad resultante"),
        ),
        migrations.AlterField(
            model_name="stockproducto",
            name="cantidad",
            field=models.IntegerField(default=0, verbose_name="cantidad"),
        ),
    ]
