# Generated by Django 6.0.5 on 2026-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0010_alter_movimientostock_resultante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="codigo_postal",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="codigo postal"
            ),
        ),
    ]
