# Generated by Django 6.0.5 on 2026-07-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_cliente_email_comprobante_cliente_email"),
        ("inventario", "0012_unificar_sucursales"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="facturacion.cliente",
                verbose_name="cliente",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="comprobante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="facturacion.comprobante",
                verbose_name="factura de esta venta",
            ),
        ),
    ]
