# Generated by Django 6.0.5 on 2026-07-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0013_venta_cliente_venta_comprobante"),
        ("precios_service", "0006_cotizaciondolarblue"),
        ("productos", "0003_producto_costo_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemventa",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="descripcion"
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="item_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_venta",
                to="precios_service.itemservice",
                verbose_name="item de la lista de service",
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("producto", "Producto del catalogo"),
                    ("service", "Service / reparacion"),
                    ("otro", "Otro"),
                ],
                default="producto",
                max_length=12,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_venta",
                to="productos.producto",
                verbose_name="producto",
            ),
        ),
    ]
