# Generated by Django 6.0.5 on 2026-07-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0014_itemventa_descripcion_itemventa_item_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medio",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="medio de pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="monto ($)"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="inventario.venta",
                        verbose_name="venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago de la venta",
                "verbose_name_plural": "pagos de la venta",
                "db_table": "inventario_ventas_pagos",
                "ordering": ("id",),
            },
        ),
    ]
