# Generated by Django 6.0.5 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0016_pagos_de_ventas_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="facturacion",
            field=models.CharField(
                choices=[
                    ("factura_ri", "Factura A/B (Responsable Inscripto)"),
                    ("factura_c", "Factura C (Monotributo)"),
                    ("sin_factura", "Sin factura"),
                ],
                default="sin_factura",
                help_text="Como se factura ESTA parte: decide a que caja entra.",
                max_length=20,
                verbose_name="facturacion",
            ),
        ),
    ]
