# Generated by Django 6.0.5 on 2026-07-29 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0006_emisor_responsable_yb"),
        ("inventario", "0018_facturacion_de_pagos_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="emisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_venta",
                to="facturacion.emisor",
                verbose_name="cuenta que factura",
            ),
        ),
    ]
