# Generated by Django 6.0.5 on 2026-09-10 01:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0020_alter_pagoventa_medio_alter_venta_forma_pago"),
        ("productos", "0005_marcar_concepto_generico_factura"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaciadoStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "sucursales_nombres",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="sucursales (foto)"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="motivo"),
                ),
                (
                    "productos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="productos respaldados"
                    ),
                ),
                (
                    "unidades",
                    models.IntegerField(default=0, verbose_name="unidades borradas"),
                ),
                (
                    "valor_lista",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cuanta plata representaba lo borrado, a precio de lista del momento.",
                        max_digits=16,
                        verbose_name="valor a lista ($)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("guardado", "Guardado (se puede restaurar)"),
                            ("restaurado", "Restaurado"),
                        ],
                        default="guardado",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "modo_restauracion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reemplazar", "Dejar el stock como estaba"),
                            ("sumar", "Sumar lo guardado a lo que hay hoy"),
                        ],
                        max_length=12,
                        verbose_name="modo de restauracion",
                    ),
                ),
                (
                    "restaurado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de restauracion"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "restaurado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="restaurado por",
                    ),
                ),
                (
                    "sucursales",
                    models.ManyToManyField(
                        related_name="vaciados",
                        to="inventario.sucursal",
                        verbose_name="sucursales vaciadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaciado de stock",
                "verbose_name_plural": "vaciados de stock",
                "db_table": "inventario_vaciados",
                "ordering": ("-creado", "-id"),
            },
        ),
        migrations.CreateModel(
            name="VaciadoStockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producto_nombre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="producto (foto)"
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="cantidad guardada")),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="stock minimo"
                    ),
                ),
                (
                    "sin_dato",
                    models.BooleanField(default=False, verbose_name="sin dato"),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="productos.producto",
                        verbose_name="producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inventario.sucursal",
                        verbose_name="sucursal",
                    ),
                ),
                (
                    "vaciado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventario.vaciadostock",
                        verbose_name="vaciado",
                    ),
                ),
            ],
            options={
                "verbose_name": "fila respaldada",
                "verbose_name_plural": "filas respaldadas",
                "db_table": "inventario_vaciados_items",
                "ordering": ("-cantidad", "id"),
                "indexes": [
                    models.Index(
                        fields=["vaciado", "sucursal"],
                        name="inventario__vaciado_08f8b8_idx",
                    )
                ],
            },
        ),
    ]
