# Generated by Django 6.0.5 on 2026-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0021_vaciadostock_vaciadostockitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="fuera_de_circuito",
            field=models.BooleanField(default=False, verbose_name="fuera del circuito"),
        ),
        migrations.AddField(
            model_name="venta",
            name="desvio_circuito",
            field=models.JSONField(
                blank=True, null=True, verbose_name="desvio del circuito"
            ),
        ),
    ]
