# Generated by Django 6.0.5 on 2026-07-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0002_seed_cotizaciones_excel"),
        ("precios_service", "0005_renombrar_etiquetas"),
    ]

    operations = [
        migrations.AddField(
            model_name="modeloequipo",
            name="dispositivo",
            field=models.ForeignKey(
                blank=True,
                help_text="Puente al catalogo unico de equipos (alimenta la Ficha de equipo). Se completa solo si el nombre coincide.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modelos_cotizacion",
                to="precios_service.dispositivo",
                verbose_name="equipo del catalogo",
            ),
        ),
    ]
