# Generated by Django 6.0.5 on 2026-07-04 19:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("precios_service", "0005_renombrar_etiquetas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "nota",
                    models.TextField(
                        blank=True,
                        help_text="Garantia y condiciones que se muestran en la seccion.",
                        verbose_name="nota",
                    ),
                ),
                (
                    "descuento_cash_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vacio = usa el global. Auriculares y smartwatch usan 30.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="descuento cash propio (%)",
                    ),
                ),
                (
                    "redondeo_ars",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vacio = usa el global ($100). Samsung/Apple usan $1.000.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="redondeo lista propio ($)",
                    ),
                ),
                (
                    "muestra_cash",
                    models.BooleanField(
                        default=True,
                        help_text="Samsung y Apple no tienen precio cash: va lista + cuotas.",
                        verbose_name="muestra precio cash",
                    ),
                ),
                (
                    "tarifa_cuotas",
                    models.CharField(
                        choices=[("accesorios", "Accesorios"), ("equipos", "Equipos")],
                        default="accesorios",
                        help_text="Que tabla del simulador de tarjetas aplica a esta categoria.",
                        max_length=20,
                        verbose_name="tarifa de cuotas",
                    ),
                ),
                (
                    "es_equipo",
                    models.BooleanField(
                        default=False,
                        help_text="En la Ficha de equipo, sus productos salen como VENTA (no como accesorio compatible).",
                        verbose_name="es venta de equipos",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijas",
                        to="productos.categoriaproducto",
                        verbose_name="categoria madre",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria de producto",
                "verbose_name_plural": "categorias de producto",
                "db_table": "productos_categorias",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionProductos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "descuento_cash_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20"),
                        help_text="Descuento global por pago cash. Las categorias pueden pisarlo.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="descuento cash (%)",
                    ),
                ),
                (
                    "redondeo_lista_ars",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="La lista en pesos se redondea PARA ARRIBA a este multiplo.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="redondeo lista ($)",
                    ),
                ),
                (
                    "redondeo_cash_ars",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="El cash en pesos se redondea PARA ARRIBA a este multiplo.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="redondeo cash ($)",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuracion de productos",
                "verbose_name_plural": "configuracion de productos",
                "db_table": "productos_configuracion",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "marca",
                    models.CharField(blank=True, max_length=60, verbose_name="marca"),
                ),
                (
                    "calidad",
                    models.CharField(
                        blank=True,
                        help_text='Ej: "Calidad original", "Apple original", "Original".',
                        max_length=60,
                        verbose_name="calidad",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        help_text='Aclaracion de la fila (ej: "x2 $6.000", "precio si compran equipo").',
                        max_length=200,
                        verbose_name="nota",
                    ),
                ),
                (
                    "a_pedido",
                    models.BooleanField(
                        default=False,
                        help_text="Requiere seña previa (no hay stock inmediato).",
                        verbose_name="a pedido",
                    ),
                ),
                (
                    "nuevo",
                    models.BooleanField(default=False, verbose_name="producto nuevo"),
                ),
                (
                    "precio_lista_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio de lista (USD)",
                    ),
                ),
                (
                    "precio_cash_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="override cash (USD)",
                    ),
                ),
                (
                    "precio_lista_ars",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="override lista ($)",
                    ),
                ),
                (
                    "precio_cash_ars",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="override cash ($)",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="productos.categoriaproducto",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "dispositivos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Para la Ficha de equipo: el equipo que ES o con los que es compatible.",
                        related_name="productos",
                        to="precios_service.dispositivo",
                        verbose_name="equipos vinculados",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "db_table": "productos_items",
                "ordering": ("orden", "id"),
            },
        ),
    ]
