# Generated by Django 6.0.5 on 2026-07-14 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_seed_accesorios_excel"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="costo_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo de reposicion. Solo lo ven los administradores.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="costo (USD)",
            ),
        ),
    ]
