# Generated by Django 6.0.5 on 2026-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_costo_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="concepto_generico_factura",
            field=models.BooleanField(
                default=False,
                help_text="En la factura este producto NO figura por su nombre: se agrupa en un renglon con el mensaje configurado en Facturacion. Marcado en parlantes, consolas y equipos Xiaomi/Samsung/Apple.",
                verbose_name="concepto generico en factura",
            ),
        ),
    ]
