# Generated by Django 6.0.5 on 2026-09-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_marcar_concepto_generico_factura"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproducto",
            name="es_service",
            field=models.BooleanField(
                default=False,
                help_text="Repuestos y mano de obra del taller (baterias, modulos, camaras, reparaciones). En Inventario se pueden filtrar aparte de la mercaderia. Lo marca solo la importacion de la planilla: en el archivo estas categorias vienen pintadas de amarillo.",
                verbose_name="es del taller (service)",
            ),
        ),
    ]
