# Generated by Django 6.0.5 on 2026-07-15 12:02

import caja.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0004_alter_movimientostock_tipo_venta_itemventa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "caja",
                "verbose_name_plural": "cajas",
                "db_table": "caja_cajas",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "cierre_ciego",
                    models.BooleanField(
                        default=True,
                        help_text="Quien cuenta no ve el esperado del efectivo; se revela al confirmar.",
                        verbose_name="cierre ciego",
                    ),
                ),
                (
                    "tolerancia_activa",
                    models.BooleanField(default=True, verbose_name="tolerancia activa"),
                ),
                (
                    "tolerancia_monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000"),
                        help_text="Si la diferencia supera este monto, el cierre exige motivo y nota.",
                        max_digits=12,
                        verbose_name="tolerancia ($)",
                    ),
                ),
                (
                    "retiros_habilitados",
                    models.BooleanField(default=True, verbose_name="retiros a boveda"),
                ),
                (
                    "multi_caja",
                    models.BooleanField(
                        default=False,
                        help_text="Varias cajas nombradas, cada una con su turno y su arqueo.",
                        verbose_name="multi-caja",
                    ),
                ),
                (
                    "exigir_lote",
                    models.BooleanField(
                        default=True,
                        help_text="Si hubo ventas con tarjeta, el pre-cierre pide confirmar el lote.",
                        verbose_name="exigir cierre de lote",
                    ),
                ),
                (
                    "fondo_sugerido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000"),
                        max_digits=12,
                        verbose_name="fondo sugerido ($)",
                    ),
                ),
                (
                    "denominaciones",
                    models.JSONField(
                        default=caja.models._denominaciones_default,
                        verbose_name="denominaciones",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuracion de caja",
                "verbose_name_plural": "configuracion de caja",
                "db_table": "caja_configuracion",
            },
        ),
        migrations.CreateModel(
            name="SesionCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="numero de turno")),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierta", "Abierta"), ("cerrada", "Cerrada")],
                        default="abierta",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "fondo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="fondo inicial ($)",
                    ),
                ),
                (
                    "conteo_apertura",
                    models.JSONField(
                        blank=True,
                        help_text="Desglose de billetes del fondo, si se conto al abrir.",
                        null=True,
                        verbose_name="conteo de apertura",
                    ),
                ),
                (
                    "nota_apertura",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nota de apertura"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones",
                        to="caja.caja",
                        verbose_name="caja",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "turno de caja",
                "verbose_name_plural": "turnos de caja",
                "db_table": "caja_sesiones",
                "ordering": ("-creado", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MovimientoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("ingreso", "Ingreso"),
                            ("egreso", "Egreso"),
                            ("retiro", "Retiro a boveda"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "medio",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                            ("otro", "Otro"),
                        ],
                        default="efectivo",
                        max_length=20,
                        verbose_name="medio de pago",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="monto ($)"
                    ),
                ),
                ("motivo", models.CharField(max_length=200, verbose_name="motivo")),
                (
                    "detalle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="detalle"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        help_text="La venta de mostrador que genero este movimiento, si aplica.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_caja",
                        to="inventario.venta",
                        verbose_name="venta",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="caja.sesioncaja",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de caja",
                "verbose_name_plural": "movimientos de caja",
                "db_table": "caja_movimientos",
                "ordering": ("creado", "id"),
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(unique=True, verbose_name="numero Z"),
                ),
                (
                    "caja_nombre",
                    models.CharField(max_length=120, verbose_name="caja (al cierre)"),
                ),
                (
                    "ventas_por_medio",
                    models.JSONField(
                        default=caja.models._dict_medios,
                        verbose_name="ventas por medio",
                    ),
                ),
                (
                    "operaciones_por_medio",
                    models.JSONField(
                        default=caja.models._dict_medios,
                        verbose_name="operaciones por medio",
                    ),
                ),
                (
                    "ingresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="ingresos ($)",
                    ),
                ),
                (
                    "egresos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="egresos ($)",
                    ),
                ),
                (
                    "retiros",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="retiros ($)",
                    ),
                ),
                (
                    "esperado_por_medio",
                    models.JSONField(
                        default=caja.models._dict_medios,
                        verbose_name="esperado por medio",
                    ),
                ),
                (
                    "contado_por_medio",
                    models.JSONField(
                        default=caja.models._dict_medios,
                        verbose_name="contado por medio",
                    ),
                ),
                (
                    "conteo_cierre",
                    models.JSONField(
                        blank=True, null=True, verbose_name="conteo de billetes"
                    ),
                ),
                (
                    "diferencia_por_medio",
                    models.JSONField(
                        default=caja.models._dict_medios,
                        verbose_name="diferencia por medio",
                    ),
                ),
                (
                    "diferencia_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Positivo = sobrante, negativo = faltante.",
                        max_digits=14,
                        verbose_name="diferencia total ($)",
                    ),
                ),
                (
                    "motivo_diferencia",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="motivo de la diferencia",
                    ),
                ),
                (
                    "nota_diferencia",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="nota de la diferencia"
                    ),
                ),
                (
                    "cierre_ciego",
                    models.BooleanField(
                        default=False, verbose_name="arqueo en modo ciego"
                    ),
                ),
                (
                    "fondo_siguiente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="fondo que queda ($)",
                    ),
                ),
                (
                    "retiro_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="retirado al cerrar ($)",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "sesion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cierre",
                        to="caja.sesioncaja",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "cierre de caja (Z)",
                "verbose_name_plural": "cierres de caja (Z)",
                "db_table": "caja_cierres",
                "ordering": ("-numero",),
            },
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False)),
                fields=("nombre",),
                name="uq_caja_viva",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesioncaja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False), ("estado", "abierta")),
                fields=("caja",),
                name="uq_sesion_abierta_por_caja",
            ),
        ),
    ]
