# Generated by Django 6.0.5 on 2026-07-22 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0002_seed_caja_principal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caja",
            name="canal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("factura_ri", "Facturado RI (Factura A/B)"),
                    ("general", "Monotributo y sin factura"),
                ],
                default="",
                help_text="Que ventas entran solas a esta caja segun como se facturan.",
                max_length=20,
                verbose_name="canal fiscal",
            ),
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("borrado", False), models.Q(("canal", ""), _negated=True)
                ),
                fields=("canal",),
                name="uq_canal_caja_viva",
            ),
        ),
    ]
