# Generated by Django 6.0.5 on 2026-07-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0004_seed_cajas_fiscales"),
        ("inventario", "0018_facturacion_de_pagos_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocaja",
            name="pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_caja",
                to="inventario.pagoventa",
                verbose_name="parte del cobro",
            ),
        ),
    ]
