# Generated by Django 6.0.5 on 2026-08-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0005_movimientocaja_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocaja",
            name="medio",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("transf_financiera", "Transferencia financiera"),
                    ("tarjeta", "Tarjeta"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=20,
                verbose_name="medio de pago",
            ),
        ),
    ]
