# Generated by Django 6.0.5 on 2026-09-14 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0006_alter_movimientocaja_medio"),
        ("inventario", "0021_vaciadostock_vaciadostockitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="caja",
            name="uq_caja_viva",
        ),
        migrations.RemoveConstraint(
            model_name="caja",
            name="uq_canal_caja_viva",
        ),
        migrations.AddField(
            model_name="caja",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cajas",
                to="inventario.sucursal",
                verbose_name="sucursal",
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="sucursal_nombre",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="sucursal (al cierre)"
            ),
        ),
        migrations.AddField(
            model_name="configuracioncaja",
            name="por_sucursal",
            field=models.BooleanField(
                default=False,
                help_text="Cada sucursal cierra su propia caja (con sus dos cajas fiscales).",
                verbose_name="caja por sucursal",
            ),
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False), ("sucursal__isnull", True)),
                fields=("nombre",),
                name="uq_caja_viva",
            ),
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False), ("sucursal__isnull", False)),
                fields=("sucursal", "nombre"),
                name="uq_caja_viva_sucursal",
            ),
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("borrado", False),
                    ("sucursal__isnull", True),
                    models.Q(("canal", ""), _negated=True),
                ),
                fields=("canal",),
                name="uq_canal_caja_viva",
            ),
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("borrado", False),
                    ("sucursal__isnull", False),
                    models.Q(("canal", ""), _negated=True),
                ),
                fields=("sucursal", "canal"),
                name="uq_canal_caja_viva_sucursal",
            ),
        ),
    ]
