# Generated by Django 6.0.5 on 2026-09-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0007_caja_por_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierrecaja",
            name="otros_medios_controlados",
            field=models.BooleanField(
                default=True, verbose_name="transferencias y tarjetas revisadas"
            ),
        ),
        migrations.AddField(
            model_name="cierrecaja",
            name="tareas_confirmadas",
            field=models.JSONField(
                blank=True, default=list, verbose_name="tareas tildadas antes de cerrar"
            ),
        ),
        migrations.AddField(
            model_name="configuracioncaja",
            name="controlar_otros_medios",
            field=models.BooleanField(
                default=True,
                help_text="Al cerrar se pregunta si lo anotado coincide con el banco y el posnet. Apagado, se toma lo que anoto el sistema.",
                verbose_name="revisar transferencias y tarjetas",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncaja",
            name="modo_conteo",
            field=models.CharField(
                choices=[
                    ("billetes", "Billete por billete"),
                    ("total", "Escribiendo el total"),
                    ("elegir", "Que elija quien cierra"),
                ],
                default="billetes",
                help_text="Billete por billete con la grilla, escribiendo el total, o que elija quien cierra.",
                max_length=10,
                verbose_name="como se cuenta el efectivo",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncaja",
            name="modo_fondo",
            field=models.CharField(
                choices=[
                    ("preguntar", "Preguntar cada vez"),
                    ("fijo", "Siempre el mismo monto"),
                    ("todo", "Dejar toda la plata en la caja"),
                ],
                default="preguntar",
                help_text="Preguntar cuanto se deja, dejar siempre el fondo sugerido, o dejar todo.",
                max_length=10,
                verbose_name="plata que queda para el proximo turno",
            ),
        ),
        migrations.AddField(
            model_name="configuracioncaja",
            name="tareas_cierre",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lo que quien cierra tiene que tildar antes de contar la plata.",
                verbose_name="tareas antes de cerrar",
            ),
        ),
    ]
