# Generated by Django 6.0.5 on 2026-07-03 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("precios_service", "0002_seed_precios_service_excel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "linea",
                    models.CharField(
                        blank=True,
                        help_text='Agrupa para el filtro por linea: "11" junta a 11, 11 Pro y 11 Pro Max.',
                        max_length=40,
                        verbose_name="linea",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "dispositivo",
                "verbose_name_plural": "dispositivos",
                "db_table": "precios_service_dispositivos",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.AddField(
            model_name="itemservice",
            name="dispositivos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipos a los que aplica esta fila (alimenta el selector de la pagina).",
                related_name="items",
                to="precios_service.dispositivo",
                verbose_name="dispositivos",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispositivo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False)),
                fields=("nombre",),
                name="uq_dispositivo_vivo",
            ),
        ),
    ]
