# Generated by Django 6.0.5 on 2026-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("precios_service", "0006_cotizaciondolarblue"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemservice",
            name="concepto_generico_factura",
            field=models.BooleanField(
                default=False,
                help_text="En la factura esta fila NO figura por su nombre: se agrupa en un renglon con el mensaje configurado en Facturacion. Marcado en los repuestos (baterias, modulos, camaras, flex, placas, tapas).",
                verbose_name="concepto generico en factura",
            ),
        ),
    ]
