# Generated by Django 6.0.5 on 2026-10-05 11:49
"""Dolar automatico (sigue al blue con una regla) e historial del dolar.

Ademas de los campos, RECONSTRUYE el historial previo: la auditoria ya venia
registrando cada edicion del dolar (antes -> despues, quien y cuando), asi que
de ahi salen las filas «vigente desde / hasta» anteriores a esta migracion. Si
no hay auditoria (base nueva) queda una sola fila con el valor actual.
"""
import datetime
from decimal import Decimal, InvalidOperation

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

ETIQUETA_DOLAR = 'dolar service'  # verbose_name del campo: la clave en `cambios`


def _decimal(texto):
    try:
        return Decimal(str(texto).replace(',', '.')).quantize(Decimal('0.01'))
    except (InvalidOperation, ValueError, TypeError):
        return None


def reconstruir_historial(apps, schema_editor):
    ConfiguracionService = apps.get_model('precios_service', 'ConfiguracionService')
    HistorialDolar = apps.get_model('precios_service', 'HistorialDolar')
    RegistroAuditoria = apps.get_model('auditoria', 'RegistroAuditoria')

    config = ConfiguracionService.objects.filter(pk=1).first()
    if config is None or HistorialDolar.objects.exists():
        return
    actual = _decimal(config.dolar)
    if actual is None:
        return

    # (valor, desde, usuario_id, username, origen), en orden cronologico.
    filas = []
    registros = RegistroAuditoria.objects.filter(
        app='precios_service', modelo='configuracion de service', accion='editar',
    ).order_by('creado', 'id')
    for registro in registros:
        cambio = (registro.cambios or {}).get(ETIQUETA_DOLAR)
        if not isinstance(cambio, dict):
            continue
        antes, despues = _decimal(cambio.get('antes')), _decimal(cambio.get('despues'))
        if despues is None:
            continue
        if not filas and antes is not None:
            # Lo que regia antes del primer cambio auditado. Desde cuando no se
            # sabe: la fecha de alta de la configuracion si es anterior, y si no
            # un instante antes de ese primer cambio.
            un_instante_antes = registro.creado - datetime.timedelta(seconds=1)
            desde = (
                config.creado
                if config.creado and config.creado < registro.creado
                else un_instante_antes
            )
            filas.append((antes, desde, None, '', 'inicial'))
        filas.append((despues, registro.creado, registro.usuario_id, registro.usuario_username or '', 'manual'))

    if not filas or filas[-1][0] != actual:
        # Sin auditoria, o el valor cambio por fuera de ella (seed, comando):
        # el actual arranca donde dice la configuracion.
        desde = config.actualizado or config.creado or timezone.now()
        if filas and desde <= filas[-1][1]:
            desde = filas[-1][1] + datetime.timedelta(seconds=1)
        filas.append((actual, desde, None, '', 'inicial' if not filas else 'manual'))

    # Vigencias encadenadas y estrictamente crecientes.
    anterior_desde = None
    normalizadas = []
    for valor, desde, usuario_id, username, origen in filas:
        if anterior_desde is not None and desde <= anterior_desde:
            desde = anterior_desde + datetime.timedelta(seconds=1)
        normalizadas.append([valor, desde, usuario_id, username, origen])
        anterior_desde = desde

    objetos = []
    for indice, (valor, desde, usuario_id, username, origen) in enumerate(normalizadas):
        siguiente = normalizadas[indice + 1][1] if indice + 1 < len(normalizadas) else None
        objetos.append(HistorialDolar(
            valor=valor,
            valor_anterior=normalizadas[indice - 1][0] if indice > 0 else None,
            vigente_desde=desde,
            vigente_hasta=siguiente,
            origen=origen,
            usuario_id=usuario_id,
            usuario_username=username,
        ))
    HistorialDolar.objects.bulk_create(objetos)


class Migration(migrations.Migration):

    dependencies = [
        ("precios_service", "0008_marcar_concepto_generico_factura"),
        ("auditoria", "0002_registroauditoria_actor_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_ajuste_tipo",
            field=models.CharField(
                choices=[("monto", "Pesos fijos"), ("porcentaje", "Porcentaje")],
                default="monto",
                max_length=10,
                verbose_name="tipo de ajuste",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_ajuste_valor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Con signo: +25 suma $25 (o 25 %); -10 resta. 0 = el blue tal cual.",
                max_digits=10,
                verbose_name="ajuste",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_calculado_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuando se reviso el blue por ultima vez en modo automatico (cambie o no).",
                null=True,
                verbose_name="ultima revision automatica",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_cambio_minimo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="En automatico, no se actualiza si la diferencia con el vigente es menor a esto.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="cambio minimo",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_modo",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (lo fija una persona)"),
                    ("automatico", "Automatico (sigue al dolar blue)"),
                ],
                default="manual",
                max_length=12,
                verbose_name="como se define el dolar",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_redondeo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1"),
                help_text="El resultado se redondea al multiplo mas cercano ($1, $5, $10...). 0 = sin redondear.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="redondeo del dolar",
            ),
        ),
        migrations.AddField(
            model_name="configuracionservice",
            name="dolar_referencia",
            field=models.CharField(
                choices=[
                    ("venta", "Blue venta"),
                    ("compra", "Blue compra"),
                    ("promedio", "Promedio compra/venta"),
                ],
                default="venta",
                help_text="Sobre que cotizacion del blue se aplica el ajuste.",
                max_length=10,
                verbose_name="referencia del blue",
            ),
        ),
        migrations.CreateModel(
            name="HistorialDolar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="dolar"
                    ),
                ),
                (
                    "valor_anterior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="dolar anterior",
                    ),
                ),
                (
                    "vigente_desde",
                    models.DateTimeField(db_index=True, verbose_name="vigente desde"),
                ),
                (
                    "vigente_hasta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vigente hasta"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("manual", "Fijado a mano"),
                            ("automatico", "Calculado del blue"),
                            ("inicial", "Valor inicial (antes del historial)"),
                        ],
                        max_length=12,
                        verbose_name="origen",
                    ),
                ),
                (
                    "usuario_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="usuario (foto)"
                    ),
                ),
                (
                    "blue_compra",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="blue compra",
                    ),
                ),
                (
                    "blue_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="blue venta",
                    ),
                ),
                (
                    "blue_fecha",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha del blue"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("venta", "Blue venta"),
                            ("compra", "Blue compra"),
                            ("promedio", "Promedio compra/venta"),
                        ],
                        max_length=10,
                        verbose_name="referencia",
                    ),
                ),
                (
                    "ajuste_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monto", "Pesos fijos"),
                            ("porcentaje", "Porcentaje"),
                        ],
                        max_length=10,
                        verbose_name="tipo de ajuste",
                    ),
                ),
                (
                    "ajuste_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ajuste",
                    ),
                ),
                (
                    "redondeo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="redondeo",
                    ),
                ),
                (
                    "nota",
                    models.CharField(blank=True, max_length=200, verbose_name="nota"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial del dolar",
                "verbose_name_plural": "historial del dolar",
                "db_table": "precios_service_dolar_historial",
                "ordering": ("-vigente_desde", "-id"),
            },
        ),
        migrations.RunPython(reconstruir_historial, migrations.RunPython.noop),
    ]
