# Generated by Django 6.0.5 on 2026-06-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_simplificar_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(unique=True, verbose_name="codigo")),
                ("nombre", models.CharField(max_length=80, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripcion"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
            ],
            options={
                "verbose_name": "permiso",
                "verbose_name_plural": "permisos",
                "db_table": "permisos",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=60, unique=True, verbose_name="nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripcion"
                    ),
                ),
                (
                    "es_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Acceso total: gestiona roles, empleados y usuarios, y ve todos los modulos.",
                        verbose_name="administra el sistema",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Roles base que no se pueden eliminar.",
                        verbose_name="rol del sistema",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de alta"
                    ),
                ),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="usuarios.permiso",
                        verbose_name="permisos",
                    ),
                ),
            ],
            options={
                "verbose_name": "rol",
                "verbose_name_plural": "roles",
                "db_table": "roles",
                "ordering": ("nombre",),
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                help_text="Define a que modulos puede entrar la cuenta. Vacio = sin acceso.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="usuarios.rol",
                verbose_name="rol",
            ),
        ),
    ]
