# Generated by Django 6.0.5 on 2026-06-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_seed_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ultima_actividad",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ultima actividad"
            ),
        ),
    ]
