# Generated by Django 6.0.5 on 2026-06-24 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_seed_permiso_simulador"),
    ]

    operations = [
        migrations.AddField(
            model_name="permiso",
            name="actualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="ultima edicion",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ultima edicion por",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="borrado",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="borrado"
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="borrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="borrado por",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="creado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="fecha de alta",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AddField(
            model_name="permiso",
            name="fecha_borrado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de borrado"
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="actualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="ultima edicion",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ultima edicion por",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="borrado",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="borrado"
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="borrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="borrado por",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="fecha_borrado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de borrado"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="actualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="ultima edicion",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="actualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ultima edicion por",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="borrado",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="borrado"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="borrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="borrado por",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="creado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="fecha de alta",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="fecha_borrado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de borrado"
            ),
        ),
        migrations.AlterField(
            model_name="rol",
            name="creado",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="fecha de alta",
            ),
        ),
    ]
