# Generated by Django 6.0.5 on 2026-08-25 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0012_seed_permiso_caja"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketImpersonacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="hash del pase",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="emitido"
                    ),
                ),
                ("expira", models.DateTimeField(verbose_name="vence")),
                (
                    "usado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="canjeado"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonaciones_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="superadministrador",
                    ),
                ),
                (
                    "objetivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cuenta impersonada",
                    ),
                ),
            ],
            options={
                "verbose_name": "pase de impersonacion",
                "verbose_name_plural": "pases de impersonacion",
                "db_table": "usuarios_tickets_impersonacion",
                "ordering": ("-creado",),
            },
        ),
    ]
