# Generated by Django 6.0.5 on 2026-08-11 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empleados", "0005_unificar_sucursal_con_inventario"),
        ("inventario", "0020_alter_pagoventa_medio_alter_venta_forma_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "host",
                    models.CharField(
                        max_length=120, verbose_name="IP o host en la sucursal"
                    ),
                ),
                (
                    "puerto",
                    models.PositiveIntegerField(default=80, verbose_name="puerto"),
                ),
                (
                    "usar_https",
                    models.BooleanField(
                        default=False, verbose_name="usar HTTPS hacia el reloj"
                    ),
                ),
                (
                    "usuario_isapi",
                    models.CharField(
                        default="admin", max_length=60, verbose_name="usuario ISAPI"
                    ),
                ),
                (
                    "poll_seconds",
                    models.PositiveIntegerField(
                        default=20, verbose_name="consultar el reloj cada (seg)"
                    ),
                ),
                (
                    "overlap_seconds",
                    models.PositiveIntegerField(
                        default=180, verbose_name="ventana de solapamiento (seg)"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=10, verbose_name="timeout de red (seg)"
                    ),
                ),
                (
                    "backfill_dias",
                    models.PositiveIntegerField(
                        default=7, verbose_name="días a recuperar en la primera sync"
                    ),
                ),
                (
                    "zona_horaria",
                    models.CharField(
                        default="America/Argentina/Buenos_Aires",
                        max_length=60,
                        verbose_name="zona horaria",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        default="DS-K1A340WX",
                        max_length=60,
                        verbose_name="modelo",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="número de serie"
                    ),
                ),
                (
                    "firmware",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="firmware"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relojes",
                        to="inventario.sucursal",
                        verbose_name="sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "reloj de asistencia",
                "verbose_name_plural": "relojes de asistencia",
                "db_table": "asistencia_dispositivos",
                "ordering": ("sucursal__orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Agente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: salta-notebook-01",
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "token_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="hash del token",
                    ),
                ),
                (
                    "token_prefijo",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=12,
                        verbose_name="prefijo del token",
                    ),
                ),
                (
                    "sync_seconds",
                    models.PositiveIntegerField(
                        default=10, verbose_name="subir fichadas cada (seg)"
                    ),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=200, verbose_name="fichadas por envío"
                    ),
                ),
                (
                    "heartbeat_seconds",
                    models.PositiveIntegerField(
                        default=60, verbose_name="heartbeat cada (seg)"
                    ),
                ),
                (
                    "nivel_log",
                    models.CharField(
                        choices=[
                            ("INFO", "INFO"),
                            ("DEBUG", "DEBUG"),
                            ("WARNING", "WARNING"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="nivel de log",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="versión del agente"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nombre de la notebook"
                    ),
                ),
                (
                    "ultimo_heartbeat",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último heartbeat"
                    ),
                ),
                (
                    "iniciado_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="agente iniciado"
                    ),
                ),
                (
                    "reloj_alcanzable",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="reloj alcanzable"
                    ),
                ),
                (
                    "reloj_error",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="último error con el reloj",
                    ),
                ),
                (
                    "eventos_pendientes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="fichadas pendientes de subir"
                    ),
                ),
                (
                    "eventos_error",
                    models.PositiveIntegerField(
                        default=0, verbose_name="fichadas con error local"
                    ),
                ),
                (
                    "ultima_sync_reloj",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última lectura del reloj"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agentes",
                        to="asistencia.dispositivo",
                        verbose_name="reloj",
                    ),
                ),
            ],
            options={
                "verbose_name": "agente de sincronización",
                "verbose_name_plural": "agentes de sincronización",
                "db_table": "asistencia_agentes",
                "ordering": ("dispositivo", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Fichada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_reloj",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="número en el reloj"
                    ),
                ),
                (
                    "nombre_reloj",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nombre en el reloj"
                    ),
                ),
                (
                    "estado_mapeo",
                    models.CharField(
                        choices=[
                            ("mapeada", "Asignada a un empleado"),
                            ("sin_mapear", "Sin asignar"),
                        ],
                        default="sin_mapear",
                        max_length=12,
                        verbose_name="estado de asignación",
                    ),
                ),
                (
                    "ocurrida_en",
                    models.DateTimeField(verbose_name="fecha y hora de la fichada"),
                ),
                (
                    "recibida_en",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="recibida por el servidor",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("check_in", "Entrada"),
                            ("check_out", "Salida"),
                            ("break_out", "Salida a descanso"),
                            ("break_in", "Vuelta de descanso"),
                            ("overtime_in", "Entrada (horas extra)"),
                            ("overtime_out", "Salida (horas extra)"),
                            ("unknown", "Sin clasificar"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("face", "Rostro"),
                            ("card", "Tarjeta"),
                            ("fingerprint", "Huella"),
                            ("password", "Clave"),
                            ("remote", "Remoto"),
                            ("unknown", "Otro"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="método de verificación",
                    ),
                ),
                (
                    "origen_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="id del evento en el reloj",
                    ),
                ),
                (
                    "hash_evento",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="hash del evento"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="payload original"
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichadas",
                        to="asistencia.agente",
                        verbose_name="agente que la subió",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichadas",
                        to="asistencia.dispositivo",
                        verbose_name="reloj",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichadas",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "fichada",
                "verbose_name_plural": "fichadas",
                "db_table": "asistencia_fichadas",
                "ordering": ("-ocurrida_en", "-id"),
                "indexes": [
                    models.Index(
                        fields=["dispositivo", "-ocurrida_en"],
                        name="idx_fichada_reloj_fecha",
                    ),
                    models.Index(
                        fields=["estado_mapeo", "numero_reloj"],
                        name="idx_fichada_mapeo",
                    ),
                    models.Index(
                        fields=["empleado", "-ocurrida_en"], name="idx_fichada_empleado"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dispositivo", "hash_evento"), name="uq_fichada_hash"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("origen_id", ""), _negated=True),
                        fields=("dispositivo", "origen_id"),
                        name="uq_fichada_origen",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MapeoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "numero_reloj",
                    models.CharField(max_length=32, verbose_name="número en el reloj"),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío: vale para todos los relojes.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos",
                        to="asistencia.dispositivo",
                        verbose_name="reloj",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapeos_asistencia",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignación de número de reloj",
                "verbose_name_plural": "asignaciones de números de reloj",
                "db_table": "asistencia_mapeos_empleado",
                "ordering": ("numero_reloj",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("borrado", False)),
                        fields=("dispositivo", "numero_reloj"),
                        name="uq_mapeo_por_reloj",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("borrado", False), ("dispositivo__isnull", True)
                        ),
                        fields=("numero_reloj",),
                        name="uq_mapeo_global",
                    ),
                ],
            },
        ),
    ]
