# Generated by Django 6.0.5 on 2026-08-17 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0001_initial"),
        ("empleados", "0005_unificar_sucursal_con_inventario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapeoempleado",
            options={
                "ordering": ("numero_reloj",),
                "verbose_name": "asignación de identificador de reloj",
                "verbose_name_plural": "asignaciones de identificadores de reloj",
            },
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="backfill_dias",
            field=models.PositiveIntegerField(
                default=90, verbose_name="días a recuperar en la primera sync"
            ),
        ),
        migrations.AlterField(
            model_name="fichada",
            name="metodo",
            field=models.CharField(
                choices=[
                    ("face", "Rostro"),
                    ("card", "Tarjeta"),
                    ("fingerprint", "Huella"),
                    ("password", "Clave"),
                    ("remote", "Remoto"),
                    ("multiple", "Varios habilitados"),
                    ("unknown", "Otro"),
                ],
                default="unknown",
                max_length=16,
                verbose_name="método de verificación",
            ),
        ),
        migrations.AlterField(
            model_name="fichada",
            name="numero_reloj",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="identificador en el reloj"
            ),
        ),
        migrations.AlterField(
            model_name="mapeoempleado",
            name="numero_reloj",
            field=models.CharField(
                max_length=32, verbose_name="identificador en el reloj"
            ),
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "tolerancia_entrada",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Minutos de gracia antes de marcar la llegada como tarde.",
                        verbose_name="tolerancia de llegada (min)",
                    ),
                ),
                (
                    "tolerancia_salida",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Minutos de gracia para irse antes del horario de salida.",
                        verbose_name="tolerancia de salida (min)",
                    ),
                ),
                (
                    "minutos_antirebote",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Si alguien ficha dos veces seguidas en menos de estos minutos, se cuenta una sola vez (doble lectura del rostro).",
                        verbose_name="ignorar refichadas dentro de (min)",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "turno",
                "verbose_name_plural": "turnos",
                "db_table": "asistencia_turnos",
                "ordering": ("nombre",),
            },
        ),
        migrations.CreateModel(
            name="TramoTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="día",
                    ),
                ),
                ("hora_entrada", models.TimeField(verbose_name="entrada")),
                ("hora_salida", models.TimeField(verbose_name="salida")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramos",
                        to="asistencia.turno",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "horario del turno",
                "verbose_name_plural": "horarios del turno",
                "db_table": "asistencia_tramos_turno",
                "ordering": ("dia_semana", "hora_entrada"),
            },
        ),
        migrations.CreateModel(
            name="AsignacionTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("desde", models.DateField(verbose_name="desde")),
                (
                    "hasta",
                    models.DateField(
                        blank=True,
                        help_text="Vacío: vigente.",
                        null=True,
                        verbose_name="hasta",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos_asistencia",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="asistencia.turno",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignación de turno",
                "verbose_name_plural": "asignaciones de turno",
                "db_table": "asistencia_asignaciones_turno",
                "ordering": ("-desde",),
            },
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vacaciones", "Vacaciones"),
                            ("enfermedad", "Enfermedad"),
                            ("especial", "Licencia especial"),
                            ("franco", "Franco / día libre"),
                            ("suspension", "Suspensión"),
                            ("otro", "Otro"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("desde", models.DateField(verbose_name="desde")),
                ("hasta", models.DateField(verbose_name="hasta")),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="observación"),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "licencia",
                "verbose_name_plural": "licencias",
                "db_table": "asistencia_licencias",
                "ordering": ("-desde",),
                "indexes": [
                    models.Index(
                        fields=["empleado", "desde", "hasta"],
                        name="idx_licencia_empleado",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="turno",
            constraint=models.UniqueConstraint(
                condition=models.Q(("borrado", False)),
                fields=("nombre",),
                name="uq_turno_vivo",
            ),
        ),
    ]
