# Generated by Django 6.0.5 on 2026-08-17 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0003_rename_dia_semana_tramoturno_indice_dia"),
        ("inventario", "0020_alter_pagoventa_medio_alter_venta_forma_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tramoturno",
            options={
                "ordering": ("indice_dia", "hora_entrada"),
                "verbose_name": "horario del turno",
                "verbose_name_plural": "horarios del turno",
            },
        ),
        migrations.AddField(
            model_name="asignacionturno",
            name="desfase_ciclo",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Solo en turnos rotativos: corre el patrón N días para esta persona. Así dos empleados comparten un 2x2 en fases opuestas.",
                verbose_name="desfase en el ciclo",
            ),
        ),
        migrations.AddField(
            model_name="licencia",
            name="hora_desde",
            field=models.TimeField(blank=True, null=True, verbose_name="desde (hora)"),
        ),
        migrations.AddField(
            model_name="licencia",
            name="hora_hasta",
            field=models.TimeField(blank=True, null=True, verbose_name="hasta (hora)"),
        ),
        migrations.AddField(
            model_name="licencia",
            name="jornada_completa",
            field=models.BooleanField(default=True, verbose_name="día completo"),
        ),
        migrations.AddField(
            model_name="turno",
            name="dias_ciclo",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Solo para turnos rotativos: cada cuántos días se repite el patrón.",
                verbose_name="días del ciclo",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="fecha_inicio_ciclo",
            field=models.DateField(
                blank=True,
                help_text="Solo para turnos rotativos: el día 1 del patrón.",
                null=True,
                verbose_name="inicio del ciclo",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="tipo_ciclo",
            field=models.CharField(
                choices=[
                    ("semanal", "Semanal (mismo horario cada semana)"),
                    ("rotativo", "Rotativo (ciclo de N días)"),
                ],
                default="semanal",
                max_length=10,
                verbose_name="tipo de ciclo",
            ),
        ),
        migrations.AlterField(
            model_name="tramoturno",
            name="indice_dia",
            field=models.PositiveSmallIntegerField(
                help_text="Semanal: 0 = lunes … 6 = domingo. Rotativo: día del ciclo.",
                verbose_name="día del patrón",
            ),
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nacional", "Nacional"),
                            ("provincial", "Provincial"),
                            ("puente", "Puente turístico"),
                            ("propio", "Cierre propio"),
                        ],
                        default="nacional",
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío: aplica a todas las sucursales.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feriados",
                        to="inventario.sucursal",
                        verbose_name="sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "feriado",
                "verbose_name_plural": "feriados",
                "db_table": "asistencia_feriados",
                "ordering": ("-fecha",),
                "indexes": [models.Index(fields=["fecha"], name="idx_feriado_fecha")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("borrado", False)),
                        fields=("fecha", "sucursal"),
                        name="uq_feriado_fecha_sucursal",
                    )
                ],
            },
        ),
    ]
