# Generated by Django 6.0.5 on 2026-08-18 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0004_alter_tramoturno_options_and_more"),
        ("empleados", "0005_unificar_sucursal_con_inventario"),
        ("inventario", "0020_alter_pagoventa_medio_alter_venta_forma_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("desde", models.DateField(verbose_name="desde")),
                (
                    "hasta",
                    models.DateField(
                        blank=True,
                        help_text="Vacío: sin fecha de fin.",
                        null=True,
                        verbose_name="hasta",
                    ),
                ),
                (
                    "dias_semana",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vacío: todos los días. Si no, solo esos días va a esa sucursal.",
                        max_length=13,
                        verbose_name="días de la semana",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="motivo"),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sucursales_asistencia",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_asistencia",
                        to="inventario.sucursal",
                        verbose_name="sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignación de sucursal",
                "verbose_name_plural": "asignaciones de sucursal",
                "db_table": "asistencia_asignaciones_sucursal",
                "ordering": ("-desde", "id"),
                "indexes": [
                    models.Index(
                        fields=["empleado", "desde"], name="idx_asig_suc_empleado"
                    )
                ],
            },
        ),
    ]
