# Generated by Django 6.0.5 on 2026-08-18 20:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0005_asignacionsucursal"),
        ("empleados", "0005_unificar_sucursal_con_inventario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JustificacionInconsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("llegada_tarde", "Llegó tarde"),
                            ("salida_temprana", "Se retiró antes"),
                            ("falta_entrada", "Falta la marca de entrada"),
                            ("falta_salida", "Falta la marca de salida"),
                            ("ausencia", "Ausente sin aviso"),
                            ("pausa_excesiva", "Salida parcial demasiado larga"),
                            ("jornada_incompleta", "Trabajó menos de lo previsto"),
                            ("exceso_jornada", "Trabajó de más"),
                            ("sucursal_incorrecta", "Fichó en otra sucursal"),
                            ("trabajo_en_feriado", "Trabajó en un feriado"),
                            ("dia_no_laborable", "Trabajó en su día franco"),
                        ],
                        max_length=24,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisión"),
                            ("justificada", "Justificada"),
                            ("rechazada", "Sin justificación válida"),
                        ],
                        default="justificada",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="motivo")),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inconsistencias",
                        to="empleados.empleado",
                        verbose_name="empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "justificación de inconsistencia",
                "verbose_name_plural": "justificaciones de inconsistencias",
                "db_table": "asistencia_justificaciones",
                "ordering": ("-fecha", "empleado__apellido"),
                "indexes": [
                    models.Index(
                        fields=["fecha", "tipo"], name="idx_justificacion_fecha"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("borrado", False)),
                        fields=("empleado", "fecha", "tipo"),
                        name="uq_justificacion_viva",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReglaInconsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("llegada_tarde", "Llegó tarde"),
                            ("salida_temprana", "Se retiró antes"),
                            ("falta_entrada", "Falta la marca de entrada"),
                            ("falta_salida", "Falta la marca de salida"),
                            ("ausencia", "Ausente sin aviso"),
                            ("pausa_excesiva", "Salida parcial demasiado larga"),
                            ("jornada_incompleta", "Trabajó menos de lo previsto"),
                            ("exceso_jornada", "Trabajó de más"),
                            ("sucursal_incorrecta", "Fichó en otra sucursal"),
                            ("trabajo_en_feriado", "Trabajó en un feriado"),
                            ("dia_no_laborable", "Trabajó en su día franco"),
                        ],
                        max_length=24,
                        verbose_name="tipo",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "umbral_minutos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Qué significa depende del tipo. Vacío en llegada tarde y salida temprana: usa la tolerancia del turno.",
                        null=True,
                        verbose_name="umbral (min)",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("moderada", "Moderada"),
                            ("grave", "Grave"),
                        ],
                        default="moderada",
                        max_length=10,
                        verbose_name="severidad",
                    ),
                ),
                (
                    "requiere_justificacion",
                    models.BooleanField(
                        default=True,
                        help_text="Si no, se reporta como dato informativo y no queda pendiente.",
                        verbose_name="pedir justificación",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío: vale para todos los turnos.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="asistencia.turno",
                        verbose_name="turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de inconsistencia",
                "verbose_name_plural": "reglas de inconsistencia",
                "db_table": "asistencia_reglas_inconsistencia",
                "ordering": ("tipo", "turno__nombre"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("borrado", False)),
                        fields=("tipo", "turno"),
                        name="uq_regla_tipo_turno",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("borrado", False), ("turno__isnull", True)),
                        fields=("tipo",),
                        name="uq_regla_global",
                    ),
                ],
            },
        ),
    ]
