# Generated by Django 6.0.5 on 2026-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0007_reglas_recomendadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivo",
            name="reintento_pedido",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="último pedido de reintento",
            ),
        ),
    ]
