# Generated by Django 6.0.5 on 2026-08-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0008_dispositivo_reintento_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="agente",
            name="reloj_bloqueado_hasta",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="reloj bloqueado hasta"
            ),
        ),
    ]
