# Generated by Django 6.0.5 on 2026-08-28 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0009_agente_reloj_bloqueado_hasta"),
        ("inventario", "0020_alter_pagoventa_medio_alter_venta_forma_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "controla",
                    models.BooleanField(
                        default=True,
                        help_text="Apagado: sus jornadas no se evalúan (ni ausencias, ni tarde, ni inconsistencias). Las fichadas se siguen registrando.",
                        verbose_name="controlar la asistencia",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="motivo"),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "sucursal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_asistencia",
                        to="inventario.sucursal",
                        verbose_name="sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "control de asistencia por sucursal",
                "verbose_name_plural": "control de asistencia por sucursal",
                "db_table": "asistencia_control_sucursal",
                "ordering": ("sucursal__orden", "sucursal__nombre"),
            },
        ),
    ]
