# Generated by Django 6.0.5 on 2026-07-30 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="usuario (foto)"
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Creo"),
                            ("editar", "Edito"),
                            ("eliminar", "Elimino"),
                            ("restaurar", "Restauro"),
                            ("ingreso", "Inicio sesion"),
                        ],
                        max_length=12,
                        verbose_name="accion",
                    ),
                ),
                (
                    "app",
                    models.CharField(blank=True, max_length=50, verbose_name="modulo"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=80, verbose_name="modelo"),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="id del objeto"
                    ),
                ),
                (
                    "objeto",
                    models.CharField(blank=True, max_length=300, verbose_name="objeto"),
                ),
                (
                    "cambios",
                    models.JSONField(blank=True, default=dict, verbose_name="cambios"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "registros de auditoria",
                "db_table": "auditoria_registros",
                "ordering": ("-creado", "-id"),
                "indexes": [
                    models.Index(
                        fields=["usuario_username", "-creado"],
                        name="auditoria_r_usuario_b24082_idx",
                    ),
                    models.Index(
                        fields=["accion", "-creado"],
                        name="auditoria_r_accion_36f7aa_idx",
                    ),
                    models.Index(
                        fields=["app", "-creado"], name="auditoria_r_app_0de379_idx"
                    ),
                ],
            },
        ),
    ]
