# Generated by Django 6.0.5 on 2026-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroauditoria",
            name="actor_username",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="actor real"
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("crear", "Creo"),
                    ("editar", "Edito"),
                    ("eliminar", "Elimino"),
                    ("restaurar", "Restauro"),
                    ("ingreso", "Inicio sesion"),
                    ("impersonar", "Impersono"),
                ],
                max_length=12,
                verbose_name="accion",
            ),
        ),
    ]
