# Generated by Django 6.0.5 on 2026-08-05 11:55

import django.db.models.deletion
import django.utils.timezone
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de alta",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="ultima edicion",
                    ),
                ),
                (
                    "borrado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="borrado"
                    ),
                ),
                (
                    "fecha_borrado",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de borrado"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(db_index=True, max_length=40, verbose_name="tipo"),
                ),
                (
                    "tipo_nombre",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nombre del tipo"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("pos80", "Ticket POS80"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="formato",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=300,
                        upload_to=documentos.models.ruta_documento,
                        verbose_name="archivo",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nombre del archivo"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="content type"
                    ),
                ),
                (
                    "tamanio",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="tamaño (bytes)"
                    ),
                ),
                (
                    "sucursal",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="sucursal"
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="cupón / N° recibo"
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="cliente"
                    ),
                ),
                (
                    "cliente_documento",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="DNI / documento"
                    ),
                ),
                (
                    "detalle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="detalle"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe del documento cuando se puede leer del formulario.",
                        max_digits=14,
                        null=True,
                        verbose_name="total",
                    ),
                ),
                (
                    "datos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos del formulario"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ultima edicion por",
                    ),
                ),
                (
                    "borrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="borrado por",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento generado",
                "verbose_name_plural": "documentos generados",
                "db_table": "documentos_generados",
                "ordering": ("-creado", "-id"),
                "indexes": [
                    models.Index(fields=["-creado"], name="doc_gen_creado_idx"),
                    models.Index(
                        fields=["tipo", "-creado"], name="doc_gen_tipo_creado_idx"
                    ),
                ],
            },
        ),
    ]
